version: 0.2

env:
  variables:
    SNYK_TOKEN: "fbc76124-10d8-4ef1-9c85-016067774004"
    AWS_ACCOUNT_ID: "339712865909"
    AWS_DEFAULT_REGION: "ap-south-1"
    IMAGE_REPO_NAME: "devsecops"
    IMAGE_TAG: "latest"
    CONTAINER_NAME: "nodejs-app-container"
    S3_BUCKET_NAME: "image-definition-bucket"
    prowlerS3Bucket : "prowler-aws-report-bucket"

    CUSTOMER_SERVICE_REPO: "339712865909.dkr.ecr.ap-south-1.amazonaws.com/customer_service"
    ORDER_SERVICE_REPO: "339712865909.dkr.ecr.ap-south-1.amazonaws.com/order_service"
    NOTIFICATION_SERVICE_REPO: "339712865909.dkr.ecr.ap-south-1.amazonaws.com/notification_service"

phases:
  install:
    runtime-versions:
      python: 3.9
      golang: 1.18
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - GITLEAKS_VERSION="8.18.1"
      - wget "https://github.com/zricethezav/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - tar -xzf "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - mv gitleaks /usr/local/bin/
      - chmod +x /usr/local/bin/gitleaks
      - rm "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - npm install -g snyk
      - echo "Installing Hadolint"
      - wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
      - chmod +x /usr/local/bin/hadolint
      - echo "Installing Trivy"
      - VERSION=$(wget -qO- https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | awk -F '"' '{print $4}')
      - wget -O trivy.tar.gz "https://github.com/aquasecurity/trivy/releases/download/$VERSION/trivy_${VERSION#v}_Linux-64bit.tar.gz"
      - tar -xzf trivy.tar.gz
      - mv trivy /usr/local/bin/
      - rm trivy.tar.gz
      - trivy --version

      - echo "installing Prowler"
      - curl -LO https://github.com/prowler-cloud/prowler/releases/latest/download/prowler-linux-amd64
      - chmod +x prowler-linux-amd64
      - mv prowler-linux-amd64 /usr/local/bin/prowler

  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"

      - echo "Running Gitleaks for secret scanning..."
      - gitleaks detect --source . --verbose --redact || echo "No secrets found"

      - echo "Authenticating Snyk..."
      - snyk auth $SNYK_TOKEN
      - echo "**** SNYK DEPENDENCY SCANNING ****"
      - cd backend

      - echo "Running Snyk for Python service"
      - cd customer-registration
      - snyk test || echo "Python service Snyk scan completed with issues"
      - cd ..

      - echo "Running Snyk for Node.js service"
      - cd order-processing
      - snyk test || echo "Node.js service Snyk scan completed with issues"
      - cd ..

      - echo "Running Snyk for Golang service"
      - cd notification
      - snyk test || echo "Golang service Snyk scan completed with issues"
      - cd ..

      - echo "******************* Running Hadolint ***********************"
      - echo "Scanning Python service Dockerfile"
      - hadolint customer-registration/Dockerfile && echo "No issues found in Python Dockerfile" || echo "Hadolint warnings for Python service"

      - echo "Scanning Node.js service Dockerfile"
      - hadolint order-processing/Dockerfile && echo "No issues found in Node.js Dockerfile" || echo "Hadolint warnings for Node.js service"

      - echo "Scanning Golang service Dockerfile"
      - hadolint notification/Dockerfile && echo "No issues found in Golang Dockerfile" || echo "Hadolint warnings for Golang service"

      - echo "Running Prowler AWS Security Scan ..."
      - prowler -r $AWS_DEFAULT_REGION -M json -o prowler-report.json

  build:
    commands:
      - echo "************* Building Docker Images ***************"

      - echo "Building Customer Registration Docker Image"
      - cd customer-registration
      - docker build -t $CUSTOMER_SERVICE_REPO:$IMAGE_TAG .
      - cd ..

      - echo "Building Order Processing Docker Image"
      - cd order-processing
      - docker build -t $ORDER_SERVICE_REPO:$IMAGE_TAG .
      - cd ..

      - echo "Building Notification Docker Image"
      - cd notification
      - docker build -t $NOTIFICATION_SERVICE_REPO:$IMAGE_TAG .
      - cd ..

  post_build:
    commands:
      - echo "************ Post Build Phase ************"

      - echo "Scanning Docker Images with Trivy"
      - echo "Scanning Customer Image"
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $CUSTOMER_SERVICE_REPO:$IMAGE_TAG || echo "Customer Image Trivy scan completed with issues"
      - echo "Scanning Order Image"
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $ORDER_SERVICE_REPO:$IMAGE_TAG || echo "Order Image Trivy scan completed with issues"
      - echo "Scanning Notification Image"
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $NOTIFICATION_SERVICE_REPO:$IMAGE_TAG || echo "Notification Image Trivy scan completed with issues"

      - echo "Trivy Scan Completed"

      - echo "************* Tagging and Pushing Images to AWS ECR *************"

      - docker push $CUSTOMER_SERVICE_REPO:$IMAGE_TAG
      - docker push $ORDER_SERVICE_REPO:$IMAGE_TAG
      - docker push $NOTIFICATION_SERVICE_REPO:$IMAGE_TAG

      
      - echo "All Images Successfully Pushed to AWS ECR!"

      - echo "Uploading Prowler  Report to S3"
      - aws s3 cp prowler-report.json s3://$prowlerS3Bucket/prowler-report.json

      - echo "Sending Reports to AWS Security Hub"
      - prowler -r $AWS_DEFAULT_REGION -M json-asff | aws securityhub batch-import-findings --region $AWS_DEFAULT_REGION --findings file://prowler-report.json

