version: 0.2

env:
  variables:
    SNYK_TOKEN: "fbc76124-10d8-4ef1-9c85-016067774004"

phases:
  install:
    runtime-versions:
      python: 3.9
      golang: 1.18
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - GITLEAKS_VERSION="8.18.1"
      - wget "https://github.com/zricethezav/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - tar -xzf "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - mv gitleaks /usr/local/bin/
      - chmod +x /usr/local/bin/gitleaks
      - rm "gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
      - npm install -g snyk
      - echo "installing hadolint"
      - wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
      - chmod +x /usr/local/bin/hadolint

  pre_build:
    commands:
      - echo "Running Gitleaks for secret scanning..."
      - gitleaks detect --source . --verbose --redact || echo "No secrets found"
      - echo "Authenticating Snyk..."
      - snyk auth $SNYK_TOKEN
      - echo "**** SNYK DEPENDENCY SCANNING ****"
      - cd backend
      - echo "Running snyk for dependency scanning for python service"
      - cd customer-registration
      - snyk test || echo "python service snyk scan completed with issues"
      - cd ..
      - echo "Running snyk for dependency scanning for Node.js service"
      - cd order-processing
      - snyk test || echo "Node.js service snyk scan completed with issues"
      - cd ..
      - echo "Running snyk for dependency scanning for Golang service"
      - cd notification
      - snyk test || echo "Golang service snyk scan completed with issues"
      - cd ..

      - echo "*******************Hadolint Running now ***********************"
      - echo "scanning python service Docker file"
      - hadolint customer-registration/Dockerfile && echo "No issues found in Python Dockerfile" || echo "Hadolint warnings for Python service"

      - echo "scanning nodejs service Docker file"
      - hadolint order-processing/Dockerfile && echo "No issues found in Node.js Dockerfile" || echo "Hadolint warnings for node.js service"

      - echo "scanning Golang service Docker file"
      - hadolint notification/Dockerfile  && echo "No issues found in Golang Dockerfile" || echo "Hadolint warnings for node.js service"

      

  build:
    commands:
      - echo "Build phase -------------------"
      # Add your build commands here

  post_build:
    commands:
      - echo "Post build -------------------"
      # Add your post-build commands here
